export const authconstants = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOUGOUT_REQUEST:"LOUGOUT_REQUEST",
    LOUGOUT_SUCCESS:"LOUGOUT_SUCCESS",
    LOUGOUT_FAILURE:"LOUGOUT_FAILURE",
}

export const userContatnts = {
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE"
}

export const categoryConstants = {
   GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
   GET_ALL_CATEGORY_SUCCESS:"GET_ALL_CATEGORY_SUCCESS",
   GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
   ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
   ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
   ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE",
}
export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST:"GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS:"GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE:"GET_ALL_INITIAL_DATA_FAILURE"
}
export const productConstants = {
  GET_ALL_PRODUCTs_REQUEST:"GET_ALL_PRODUCTs_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE"
}